 language: scala
 scala:
   - "2.10.4"
 jdk:
   - oraclejdk7
 env:
  matrix:
   - TEST="scalastyle assembly/assembly"
   - TEST="catalyst/test sql/test streaming/test mllib/test graphx/test bagel/test"
   - TEST=hive/test
 cache:
   directories:
     - $HOME/.m2
     - $HOME/.ivy2
     - $HOME/.sbt
 script:
   - "sbt ++$TRAVIS_SCALA_VERSION $TEST"
